version: 0.0.{build}
skip_non_tags: true
image: Visual Studio 2015
init:
- ps: git config --global core.autocrlf false
environment:
  PIP: C:/Python35/Scripts/pip.exe
  PYTHON: C:/Python35/python.exe
install:
- ps: >-
    C:/Python35/Scripts/pip.exe install --upgrade pip setuptools

    C:/Python35/Scripts/pip.exe install pyinstaller

    C:/Python35/Scripts/pip.exe install -r requirements.txt

    Install-Product node ''

    npm install -g less-watch-compiler

    less-watch-compiler --run-once static/css static/css --main-file main.less
build: off
test_script:
- cmd: >-
    C:/Python35/Scripts/pyinstaller.exe ws.py --log-level CRITICAL -y -F -n server.exe
after_test:
- ps: >-
    mkdir hs

    mkdir hs/hs

    cp -r static hs/hs

    mv dist/server.exe hs/hs
artifacts:
- path: hs
  name: hs
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: aqxOwrvNEIZ2ian/bj0ZyfEzMFNWalV5zDfFqpcxfZX47FAIW9ud6kgCU2jm/fMk
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master