version: 1.3.{build}
skip_non_tags: true
image: Visual Studio 2015
init:
- ps: git config --global core.autocrlf false
environment:
  PIP: C:/Python35/Scripts/pip.exe
  PYTHON: C:/Python35/python.exe
install:
- ps: >-
    C:/Python35/Scripts/pip.exe install --upgrade pip setuptools pyinstaller

    C:/Python35/Scripts/pip.exe install -r requirements.txt

    Install-Product node ''

    npm install -g less less-plugin-clean-css html-minifier uglify-js@github:mishoo/UglifyJS2#harmony
build: off
test_script:
- cmd: >-
    C:/Python35/Scripts/pyinstaller.exe ws.py --log-level CRITICAL -y -F -n server.exe

# Prepare files and directories
after_test:
- ps: >-
    mkdir hs

    mkdir hs/hs

    lessc --clean-css="--s1 --advanced" .\static\css\main.less .\static\css\main.css

    uglifyjs --compress --mangle -o static/js/common.js static/js/common.js

    uglifyjs --compress --mangle -o static/js/vue-components.js static/js/vue-components.js

    html-minifier static/index.html --output static/index.html --html5 --remove-comments --remove-tag-whitespace --collapse-inline-tag-whitespace --remove-attribute-quotes --collapse-whitespace

    html-minifier static/statistic.html --output static/statistic.html --html5 --remove-comments --remove-tag-whitespace --collapse-inline-tag-whitespace --remove-attribute-quotes --collapse-whitespace

    html-minifier static/gamers.html --output static/gamers.html --html5 --remove-comments --remove-tag-whitespace --collapse-inline-tag-whitespace --remove-attribute-quotes --collapse-whitespace

    cp -r static hs/hs

    rm hs/hs/static/css/*.less

    mv dist/server.exe hs/hs
artifacts:
- path: hs
  name: hs
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: aqxOwrvNEIZ2ian/bj0ZyfEzMFNWalV5zDfFqpcxfZX47FAIW9ud6kgCU2jm/fMk
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: master